// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/actions/audit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/actions/audit.post').default>>>>
    }
    '/api/active-directory': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/active-directory/index.get').default>>>>
    }
    '/api/aplicaciones/accesos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/aplicaciones/accesos.get').default>>>>
    }
    '/api/aplicaciones/conceder': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/aplicaciones/conceder.post').default>>>>
    }
    '/api/aplicaciones': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/aplicaciones/index.get').default>>>>
    }
    '/api/aplicaciones/toggle-acceso': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/aplicaciones/toggle-acceso.post').default>>>>
    }
    '/api/auditorias': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auditorias/index.get').default>>>>
    }
    '/api/colaboradores/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/colaboradores/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/colaboradores/[id].put').default>>>>
    }
    '/api/colaboradores/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/colaboradores/create.post').default>>>>
    }
    '/api/colaboradores': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/colaboradores/index.get').default>>>>
    }
    '/api/dashboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard.get').default>>>>
    }
    '/api/dashboard/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/stats.get').default>>>>
    }
    '/api/desvinculacion/iniciar/:id': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/desvinculacion/iniciar/[id].post').default>>>>
    }
    '/api/desvinculacion/wizard/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/desvinculacion/wizard/[id].get').default>>>>
    }
    '/api/devices/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devices/[id].get').default>>>>
    }
    '/api/devices': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/devices/index.get').default>>>>
    }
    '/api/equipos/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/equipos/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/equipos/[id].put').default>>>>
    }
    '/api/equipos/accion': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/equipos/accion.post').default>>>>
    }
    '/api/equipos/collect': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/equipos/collect.post').default>>>>
    }
    '/api/equipos/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/equipos/create.post').default>>>>
    }
    '/api/equipos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/equipos/index.get').default>>>>
    }
    '/api/equipos/ping': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/equipos/ping.post').default>>>>
    }
    '/api/google/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/google/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/google/[id].put').default>>>>
    }
    '/api/google/auth-url': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/google/auth-url.get').default>>>>
    }
    '/api/google/callback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/google/callback.get').default>>>>
    }
    '/api/google/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/google/create.post').default>>>>
    }
    '/api/google/exchange-code': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/google/exchange-code.post').default>>>>
    }
    '/api/google/sincronizar': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/google/sincronizar.post').default>>>>
    }
    '/api/google/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/google/status.get').default>>>>
    }
    '/api/google/toggle-status': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/google/toggle-status.post').default>>>>
    }
    '/api/google/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/google/users.get').default>>>>
    }
    '/api/jira/sincronizar': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/jira/sincronizar.post').default>>>>
    }
    '/api/licenses': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/licenses/index.get').default>>>>
    }
    '/api/microsoft/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/microsoft/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/microsoft/[id].put').default>>>>
    }
    '/api/microsoft/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/microsoft/create.post').default>>>>
    }
    '/api/microsoft/sincronizar': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/microsoft/sincronizar.post').default>>>>
    }
    '/api/microsoft/toggle-status': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/microsoft/toggle-status.post').default>>>>
    }
    '/api/microsoft/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/microsoft/users.get').default>>>>
    }
    '/api/politicas/aplicar': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/politicas/aplicar.post').default>>>>
    }
    '/agent/install.ps1': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/agent/install.ps1').default>>>>
    }
    '/agent/ren-agent.js': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/agent/ren-agent.js').default>>>>
    }
    '/agent/ren-lock.ps1': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/agent/ren-lock.ps1').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}