// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/8/2026, 7:47:43 a. m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Documents/GitHub/Directorio-Activo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Documents/GitHub/Directorio-Activo/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Documents/GitHub/Directorio-Activo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Documents/GitHub/Directorio-Activo/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Documents/GitHub/Directorio-Activo/plugins/**/*.{js,ts,mjs}","D:/Documents/GitHub/Directorio-Activo/composables/**/*.{js,ts,mjs}","D:/Documents/GitHub/Directorio-Activo/utils/**/*.{js,ts,mjs}","D:/Documents/GitHub/Directorio-Activo/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Documents/GitHub/Directorio-Activo/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Documents/GitHub/Directorio-Activo/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Documents/GitHub/Directorio-Activo/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;