// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/8/2026, 11:50:29 a. m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Desktop/proyectos a estregar/Directorio 2.0/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/proyectos a estregar/Directorio 2.0/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/proyectos a estregar/Directorio 2.0/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/proyectos a estregar/Directorio 2.0/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/proyectos a estregar/Directorio 2.0/plugins/**/*.{js,ts,mjs}","D:/Desktop/proyectos a estregar/Directorio 2.0/composables/**/*.{js,ts,mjs}","D:/Desktop/proyectos a estregar/Directorio 2.0/utils/**/*.{js,ts,mjs}","D:/Desktop/proyectos a estregar/Directorio 2.0/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/proyectos a estregar/Directorio 2.0/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/proyectos a estregar/Directorio 2.0/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Desktop/proyectos a estregar/Directorio 2.0/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;